version: '3.7'

volumes:
 hm-db_vol01:
 hm-web_vol01:
 hm-logs_vol01:
 #ssl-certificates_vol01:

services:

 hm-db:
    image: docker.adipsys.com:5000/hm-ha-db
    restart: always
    command: seed    
#   command: node hm-dbX
    environment:
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    deploy:
      placement:
             #max_replicas_per_node: 1
             constraints:
                 - node.role == manager
    volumes:
          - 'hm-db_vol01:/var/lib/mysql/'

# hm-dbX:
#    image: docker.adipsys.com:5000/hm-ha-db
#    restart: always
#    command: node hm-db
#    environment:
#      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_ROOT_HOST=%
#    deploy:
#      placement:
#             #max_replicas_per_node: 1
#             constraints:
#                 - node.role != manager
#    volumes:
#          - 'hm-db_vol01:/var/lib/mysql/'
          
 hm-web:
      image: docker.adipsys.com:5000/hm-ha-web:${PRODUCT_VERSION}
      hostname: wifi-node1
      restart: always
      environment:
             - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
             - OPERATOR=${OPERATOR}
             - HM_SERVER_NAME=${HM_SERVER_NAME}
             - HM_URL_SUFFIX=${HM_URL_SUFFIX}
             - HOTSPOT_ALIAS1=${HOTSPOT_ALIAS1}
             - ADMIN_ALIAS1=${ADMIN_ALIAS1}
             - OPERATOR_SUPPORT_EMAIL=${OPERATOR_SUPPORT_EMAIL}
             - LICENCE_SERVER=licences.adipsys.com
             - RSYSLOG_SERVER=${RSYSLOG_SERVER}
             - REMEDIATION=yes
             - SYMFONY_VERSION=1.4.20
      deploy:
         placement:
             #max_replicas_per_node: 1
             constraints:
                 - node.role == manager
      ports:
              - ${WEB_IHM_PORT}:80
              - ${WEB_IHM_SSL_PORT}:443
              - 514:514/udp
      volumes:
          - 'hm-web_vol01:/var/www/hotspotmanager/prod/web/'
          - 'hm-logs_vol01:/data/logs/'
         #- 'ssl-certificates_vol01:/root/hm_ssl_certificates/'
          - '/root/ssl_certificates/:/root/hm_ssl_certificates/'
         #- '/backups/:/backups/'
      depends_on:
        - "hm-db"
        
 hm-radius:
      image: docker.adipsys.com:5000/hm-ha-radius:${PRODUCT_VERSION}
      restart: always
      #command: freeradius -fxxx
      #deploy:
         #placement:
             #max_replicas_per_node: 1
      ports:
              - ${RADIUS_AUTH_PORT}:1812/udp
              - ${RADIUS_ACC_PORT}:1813/udp
      depends_on:
        - "hm-db"
